<?php

	// tipo de vaga
	$TIPO_VAGA_CARRO = 1;
	$TIPO_VAGA_MOTO = 1;
	$TIPO_VAGA_UTILITARIO = 1;
	
	// tipo de usuário
	$TIPO_USUARIO_ADM = 1;
	$TIPO_USUARIO_CLIENTE = 2;
	
	// status de reserva
	$STATUS_RESERVA_UTILIZADA = 1;
	$STATUS_RESERVA_UTILIZACAO = 2;
	$STATUS_RESERVA_CANCELADA = 3;
	$STATUS_RESERVA_RESERVADA = 4;
	
?>
