-- MySQL Script generated by MySQL Workbench
-- 04/23/15 09:29:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema estacionamento
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `estacionamento` ;

-- -----------------------------------------------------
-- Schema estacionamento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estacionamento` ;
USE `estacionamento` ;




-- -----------------------------------------------------
-- Table `estacionamento`.`vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estacionamento`.`vehicle` ;

CREATE TABLE IF NOT EXISTS `estacionamento`.`vehicle` (
  `vehicle_id` INT(11) NOT NULL AUTO_INCREMENT,
  `plate` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `fabricator` VARCHAR(20) NULL DEFAULT NULL,
  `model` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`vehicle_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;





-- -----------------------------------------------------
-- Table `estacionamento`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estacionamento`.`user` ;

CREATE TABLE IF NOT EXISTS `estacionamento`.`user` (
  `user_id` INT(11) NOT NULL COMMENT 'O id do usuário será o seu CPF ou CNPJ',
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `type` VARCHAR(50) NOT NULL COMMENT 'Identifica a pessoa física ou juridica',
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `category` VARCHAR(45) NULL COMMENT 'identifica a categoria: cliente ou administrador',
  `cash_money` VARCHAR(45) NULL DEFAULT NULL COMMENT 'o valor que ele possui de creditos',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;





-- -----------------------------------------------------
-- Table `estacionamento`.`cost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estacionamento`.`cost` ;

CREATE TABLE IF NOT EXISTS `estacionamento`.`cost` (
  `cost_id` INT(11) NOT NULL,
  `time` VARCHAR(50) NOT NULL COMMENT 'tempo em de estacionamento',
  `cost` DOUBLE NOT NULL COMMENT 'o custo em relação ao tempo',
  PRIMARY KEY (`cost_id`),
  INDEX `idx_fk_store_id` (`time` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table storing all customers. Holds foreign keys to the addre' /* comment truncated */ /*s table and the store table where this customer is registered.

Basic information about the customer like first and last name are stored in the table itself. Same for the date the record was created and when the information was last updated.*/;


-- -----------------------------------------------------
-- Table `estacionamento`.`parking_space`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estacionamento`.`parking_space` ;

CREATE TABLE IF NOT EXISTS `estacionamento`.`parking_space` (
  `parking_space_id` INT(11) NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL COMMENT 'nomear a vaga',
  `local` VARCHAR(50) NULL DEFAULT NULL COMMENT 'local onde se encontra a vaga',
  `tipo` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Exemplo: Idoso, deficiênte, gravida, normal',
  `cost_id` INT(11) NOT NULL,
  PRIMARY KEY (`parking_space_id`, `cost_id`),
  INDEX `idx_fk_store_id` (`name` ASC),
  INDEX `fk_parking_space_cost1_idx` (`cost_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table storing all customers. Holds foreign keys to the addre' /* comment truncated */ /*s table and the store table where this customer is registered.

Basic information about the customer like first and last name are stored in the table itself. Same for the date the record was created and when the information was last updated.*/;


-- -----------------------------------------------------
-- Table `estacionamento`.`plane_vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estacionamento`.`plane_vehicle` ;

CREATE TABLE IF NOT EXISTS `estacionamento`.`plane_vehicle` (
  `plane_vehicle_id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_input` DATETIME NULL DEFAULT NULL COMMENT 'data de entrada e hora',
  `date_output` DATETIME NULL DEFAULT NULL COMMENT 'Data da saida e hora',
  `user_id` INT(11) NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  `parking_space_id` INT(11) NOT NULL,
  `parking_space_cost_id` INT(11) NOT NULL,
  PRIMARY KEY (`plane_vehicle_id`, `user_id`, `vehicle_id`, `parking_space_id`, `parking_space_cost_id`),
  INDEX `fk_user_vehicle_usuario1_idx` (`user_id` ASC),
  INDEX `fk_user_vehicle_vehicle1_idx` (`vehicle_id` ASC),
  INDEX `fk_plane_vehicle_parking_space1_idx` (`parking_space_id` ASC, `parking_space_cost_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;




-- -----------------------------------------------------
-- Table `estacionamento`.`user_vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estacionamento`.`user_vehicle` ;

CREATE TABLE IF NOT EXISTS `estacionamento`.`user_vehicle` (
  `user_space_id` INT(11) NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_space_id`, `vehicle_id`, `user_id`),
  INDEX `fk_user_vehicle_vehicle2_idx` (`vehicle_id` ASC),
  INDEX `fk_user_vehicle_usuario2_idx` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table storing all customers. Holds foreign keys to the addre' /* comment truncated */ /*s table and the store table where this customer is registered.

Basic information about the customer like first and last name are stored in the table itself. Same for the date the record was created and when the information was last updated.*/;